name: clouddrift-examples
channels:
  - conda-forge
dependencies:
  - python=3.10
  - clouddrift
  - numpy
  - xarray
  - awkward
  - netcdf4
  - pyarrow
  - tqdm
  - fsspec
  - llvmlite
  - pandas
  - tqdm
  - matplotlib
